### ISSUE TITLE
credentials.h

### ISSUE THREAD

**Issue by shinyone** [SensorsIot/Heartbeat8266#1]
Your use of <credentials.h> can make it difficult for beginners to take the code and run it.  Although obvious why you do it...

This helped  https://github.com/SensorsIot/Internet-of-Things-with-ESP8266/issues/1#issuecomment-256253771

Changed line 25 to:
`#include "credentials.h"`

Created new local .h file:
```
#define mySSID "xxxx" // wifi name
#define myPASSWORD "yyyyyyyyyyyyyy" // wifi password
#define TELEGRAM_CERTIFICATE_ROOT "cert" // telegram cert
#define CHAT_ID "zzzzzzzzz" // telegram chat id
#define ALARM_BOT_TOKEN "aaaaa" // telegram bot
```

**Comment by SensorsIot** [comment]
Thank you. I added your lines to the code
